# Generated by Django 3.1.1 on 2020-09-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorhttp', '0002_auto_20200921_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='endpoint',
            new_name='name',
        ),
    ]
